### PR TITLE
u-boot-pcie: Correct ARM/DSP speed for 16bit DDR2 h/w ID.  Add more d…

### PR DESCRIPTION
**Pull request by sgturner**
This commit apparently got missed for V10?.  Can merge and make V11?.

### CODE REVIEW

**Comment by sgturner** [comment]
Does the bootloader (i.e the code uploaded by the serial util, to upload the u-boot) respond to the engineering jumper?.  It just seems that even in v10, it can't talk to a 16bit bus (I have a card with the upper DDR2 physically removed)

**Comment by dbrignoli** [comment]
The serial boot loader should respond to the eng jumper and should work with 16bit external memory bus. You don't need to use the images that come with the utility so if you had it working using other images I provided or you compiled you can point the utility to those images. I think it would help to make sure those 'old' images still work with a card with the second DDR2 still present and then with a card with the second DDR2 removed.

**Comment by dbrignoli** [comment]
Split and merged. However, I thought the 0x3 H/W ID was an experiment and we don't know how much memory it's going to have in the end. Do you intend to permanently assign 64Mbyes to H/W ID 0x3 even if it's not going to be in production?

**Comment by andrew-elder** [comment]
Is this for sound cards only?

**Comment by andrew-elder** [comment]
I guess since it is on the uboot_pcie branch it is for PCIe devices only?

**Comment by dbrignoli** [comment]
> Is this for sound cards only?
> I guess since it is on the uboot_pcie branch it is for PCIe devices only?

Changes went to both HONO and PCIe branches. It unfortunate in the first place that there are two different branches. I brought up the H/W ID issue because we have 3 bits allocated for it and we shouldn't use them up unnecessarily.

**Comment by sgturner** [comment]
>>64Mbyes to H/W ID 0x3 even if it's not going to be in production?
This will go to production.  Currently for the ASI58xx only.

**Comment by sgturner** [comment]
Thanks @dbrignoli .  Can you give me a v11 .pyz?.

**Comment by dbrignoli** [comment]
If the v10 didn't work the v11 won't work either. I believe you had working images at some point, is that correct? If so, we need to confirm that v10 works with those images (by specifying them on the command line).

BTW, there is no difference between v9 and v10 except for the default images that it ships with.

**Comment by sgturner** [comment]
I need a new bootloader that has the v11 changes in it.  I can compile the v11 u-boot (MLO_pcie), but need the bootloader

**Comment by sgturner** [comment]
Which build is the bootloader?.  asi1230_uart_config?.  or asi1230_uart2flash?

**Comment by andrew-elder** [comment]
Which build is which bootloader, right? We have PCIe bootloader and Hono bootloader. Or, are you talking about something else completely?

**Comment by dbrignoli** [comment]
asi1230_uart2flash while on the asi1230-master branch for the serial bootloader and sh uboot-pci.sh while on the asi6700-master branch for the asi6700_v11

**Comment by dbrignoli** [comment]
> Which build is which bootloader, right? We have PCIe bootloader and Hono bootloader. Or, are you talking about something else completely?

@andrew-elder, @sgturner needs a serial bootloader to bootstrap an ASI6700 with blank SPI and then a 6700 SPI bootloader to be written into said blank SPI.

**Comment by dbrignoli** [comment]
> I need a new bootloader that has the v11 changes in it. I can compile the v11 u-boot (MLO_pcie), but need the bootloader

BTW you didn't answer my question about having working images and trying them with: normal board, 16bit wide bus with 2nd DDR2 *not* removed and finally 16bit wide bus with 2nd DDR2 removed. It seems to me you are changing too many variables at the same time so I (we?) don't know what is wrong.

**Comment by sgturner** [comment]
>> BTW you didn't answer my question

@dbrignoli - Sorry - I'm going to have to start from scratch.  Just need the "bootloader" recompiled for V11.  What I mean by bootloader is:


c:\asi\sw\utility\asi1230serialutil>python asi1230serialutil_asi6700_v10.pyz bootstrap_6700 --serial-dev \\.\COM8 --spi-
img MLO_pcie
ASI1230/ASI6700 serial utility v1.0.5

Enter board ID string: asi6788-f6-91235
Using internal UART boot image
Enable UART boot using jumper and power-on or reset the board. Waiting for transfer handshake ... received.
Uploading **bootloader** ... done.
Waiting for prompt ... timed out, retrying.
Waiting for prompt ... timed out, retrying.

**Comment by sgturner** [comment]
@dbrignoli - how do I specify the bootloader bin on the command line?

**Comment by dbrignoli** [comment]
> @dbrignoli - how do I specify the bootloader bin on the command line?

Can't remember but ```python asi1230serialutil_asi6700_v10.pyz -h``` will tell you, easy!

**Comment by dbrignoli** [comment]
> @dbrignoli - Sorry - I'm going to have to start from scratch. Just need the "bootloader" recompiled for V11.

From above:

> asi1230_uart2flash while on the asi1230-master branch for the serial bootloader and sh uboot-pci.sh while on the asi6700-master branch for asi6700_v11

**Comment by sgturner** [comment]
Don't quite see what I need here:

```
c:\asi\sw\utility\asi1230serialutil>python asi1230serialutil_asi6700_v10.pyz -h
ASI1230/ASI6700 serial utility v1.0.5

usage: asi1230serialutil [-h]

                         {create_archive,boot,console,logsave,write_bootloader,write_env,write_boardinfo,bootstrap_6700}

                         ...

ASI1230/ASI6700 serial utility

positional arguments:
  {create_archive,boot,console,logsave,write_bootloader,write_env,write_boardinfo,bootstrap_6700}
                        Which command to execute
  args                  The command's arguments

optional arguments:
  -h, --help            show this help message and exit
```

**Comment by sgturner** [comment]
Don't quite see what I need here:

```
c:\asi\sw\utility\asi1230serialutil>python asi1230serialutil_asi6700_v10.pyz -h
ASI1230/ASI6700 serial utility v1.0.5

usage: asi1230serialutil [-h]

                         {create_archive,boot,console,logsave,write_bootloader,write_env,write_boardinfo,bootstrap_6700}

                         ...

ASI1230/ASI6700 serial utility

positional arguments:
  {create_archive,boot,console,logsave,write_bootloader,write_env,write_boardinfo,bootstrap_6700}
                        Which command to execute
  args                  The command's arguments

optional arguments:
  -h, --help            show this help message and exit
```

**Comment by dbrignoli** [comment]
Sorry, I'm on my phone and I missed a bit of text when cutting and pasting, I meant:

```python asi1230serialutil_asi6700_v10.pyz bootstrap_6700 -h```

**Pull request closed without merging**
